name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    if: startsWith(github.event.head_commit.message, 'deploy')
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Print commit message
        run: |
          echo "Commit message: ${{ github.event.head_commit.message }}"
          pwd
          ls   
    
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Extract report name
        id: extract_name
        run: |
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          REPORT_NAME=$(echo $COMMIT_MSG | grep -oP 'report=\K[^,\s]+' || echo "yahoo-news-comment")
          echo "report_name=$REPORT_NAME" >> $GITHUB_OUTPUT
          echo "Using report name: $REPORT_NAME"
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'scatter/next-app/package-lock.json'
      
      - name: Install dependencies
        run: |
          cd scatter/next-app
          npm ci
      
      - name: Build
        env:
          REPORT: ${{ steps.extract_name.outputs.report_name }}
        run: |
          cd scatter/next-app
          echo "Building report: $REPORT"
          npm run build
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: scatter/pipeline/outputs/$REPORT/report

      - name: Create deployment tag
        if: success()
        run: |
          TAG_NAME="deploy-$(date +%Y%m%d-%H%M%S)"
          git tag $TAG_NAME
          git push origin $TAG_NAME
